# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d4vZSthyF9ROxx4_SnPyTDK7cYk0i7m5
"""

import numpy as np
import random as rd
sample_space=100000000
def check(arr):
    count=0
    temp=arr[0]
    for i in range(7):
        if (arr[i]==temp):
            count+=1
    if(count==7):
        return True
    else :
        return False
arr=[-1,-1,-1,-1,-1,-1,-1]
num=0.0
for i in range(sample_space):
    for j in range(7):
        arr[j]=rd.randint(1, 7)
    if(check(arr)):
        num+=1
pr=num/sample_space
print(pr)